# Generated by Django 5.1.6 on 2025-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails_web", "0003_userprofile_personal_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="personal_bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
