# Generated by Django 5.1.6 on 2025-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails_web", "0004_alter_userprofile_personal_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="trail",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="trail",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="trail",
            name="estimate_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="trail",
            name="length",
            field=models.FloatField(default=0.0),
        ),
    ]
