# Generated by Django 5.1.6 on 2025-03-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails_web", "0005_trail_latitude_trail_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_trail",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_trails",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="trails_web.trail"
            ),
        ),
    ]
