# Generated by Django 5.1.6 on 2025-03-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails_web", "0007_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_trails",
                to="trails_web.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="trail_images/"),
        ),
    ]
