# Generated by Django 5.1.6 on 2025-03-18 13:46

import trails_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails_web", "0008_trail_created_by_trail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trail",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=trails_web.models.TrailImagePath()
            ),
        ),
    ]
